set(_CATKIN_CURRENT_PACKAGE "wpg")
set(wpg_VERSION "0.1.0")
set(wpg_MAINTAINER "piradata <guilhermefercar@gmail.com>")
set(wpg_PACKAGE_FORMAT "1")
set(wpg_BUILD_DEPENDS "geometry_msgs" "mavros" "roscpp" "rospy" "std_msgs" "sensor_msgs" "message_generation" "libmavconn")
set(wpg_BUILD_EXPORT_DEPENDS "mavros" "geometry_msgs" "roscpp" "std_msgs" "sensor_msgs" "rospy" "libmavconn" "message_runtime")
set(wpg_BUILDTOOL_DEPENDS "catkin")
set(wpg_BUILDTOOL_EXPORT_DEPENDS )
set(wpg_EXEC_DEPENDS "mavros" "geometry_msgs" "roscpp" "std_msgs" "sensor_msgs" "rospy" "libmavconn" "message_runtime")
set(wpg_RUN_DEPENDS "mavros" "geometry_msgs" "roscpp" "std_msgs" "sensor_msgs" "rospy" "libmavconn" "message_runtime")
set(wpg_TEST_DEPENDS )
set(wpg_DOC_DEPENDS )
set(wpg_URL_WEBSITE "")
set(wpg_URL_BUGTRACKER "")
set(wpg_URL_REPOSITORY "")
set(wpg_DEPRECATED "")